packages:
  - packages/*

minimumReleaseAge: 10080

onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd

patchedDependencies:
  '@cloudflare/vitest-pool-workers@0.12.7': patches/@cloudflare__vitest-pool-workers@0.12.7.patch
