packages:
  - packages/*

minimumReleaseAge: 1440 # 24 hours
trustPolicy: no-downgrade
blockExoticSubdeps: true

catalog:
  "wrangler": 4.73.0 
  "@cloudflare/vitest-pool-workers": 0.13.0
  "@cloudflare/workers-types": 4.20260312.1
  "@types/node": 25.5.0

catalogMode: manual
cleanupUnusedCatalogs: true

onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd
